projectType: runtime
jdkTool: OPEN-JDK11
testJdkTool: OPEN-JDK8
additionalTestConfigs:
  jdk11:
    testJdkTool: OPEN-JDK11
# TODO W-14854013 reenable this version
#  jdk17:
#    testJdkTool: OPEN-JDK17
